name: Package Validation

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  validate:
    name: Shared package validation
    uses: Deucarian/Package-Registry/.github/workflows/deucarian-package-validation.yml@7e6a1f8041c9ec35cd1307abaf28692c0edb4bf0 # Package Registry main
    with:
      registry-ref: 7e6a1f8041c9ec35cd1307abaf28692c0edb4bf0 # Package Registry main
      package-config: deucarian-package.json
